version: '3'
services:
  daemon:
    build: .
    container_name: daemon
    volumes:
      - /home/ubuntu/scheduler:/root
    network_mode: "host"
    command: python3 worker_daemon.py --port=8888

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/root/scheduler/checkpoints/data:/home/username/"
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: test
      FTP_USER_PASS: test
      FTP_USER_HOME: /home/username
    restart: always