version: '3'
services:
  ps0:
    build: .
    networks:
      - cluster
    command: python3 worker_daemon.py --port=8888

  ps1:
    build: .
    networks:
      - cluster
    command: python3 worker_daemon.py --port=8888

  worker0:
    build: .
    networks:
      - cluster
    command: python3 worker_daemon.py --port=8888

  worker1:
    build: .
    networks:
      - cluster
    command: python3 worker_daemon.py --port=8888

  master:
    build: .
    networks:
      - cluster
    command: bash

networks:
  cluster: