version: '3'
services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    volumes:
      - "/home/ubuntu/scheduler/:/home/"
    environment:
      PUBLICHOST: ${PUBLIC_IP}
      FTP_USER_NAME: checkpoints
      FTP_USER_PASS: test
      FTP_USER_HOME: /home/
      FTP_MAX_CLIENTS: 50
      FTP_PASSIVE_PORTS: "30000:30099"
    restart: always